-- Seed the 48 World Cup 2026 teams.
-- Groups will be filled in once FIFA finalizes the draw (Dec 2025).
-- Group letters here are placeholders — re-run UPDATE statements when draw is known.

insert into teams (id, name, flag_emoji) values
  ('CAN','Canada','🇨🇦'),
  ('MEX','Mexico','🇲🇽'),
  ('USA','United States','🇺🇸'),
  ('ARG','Argentina','🇦🇷'),
  ('BRA','Brazil','🇧🇷'),
  ('URU','Uruguay','🇺🇾'),
  ('COL','Colombia','🇨🇴'),
  ('ECU','Ecuador','🇪🇨'),
  ('PAR','Paraguay','🇵🇾'),
  ('VEN','Venezuela','🇻🇪'),
  ('ENG','England','🏴󠁧󠁢󠁥󠁮󠁧󠁿'),
  ('FRA','France','🇫🇷'),
  ('ESP','Spain','🇪🇸'),
  ('GER','Germany','🇩🇪'),
  ('POR','Portugal','🇵🇹'),
  ('NED','Netherlands','🇳🇱'),
  ('BEL','Belgium','🇧🇪'),
  ('ITA','Italy','🇮🇹'),
  ('CRO','Croatia','🇭🇷'),
  ('SUI','Switzerland','🇨🇭'),
  ('AUT','Austria','🇦🇹'),
  ('DEN','Denmark','🇩🇰'),
  ('NOR','Norway','🇳🇴'),
  ('SCO','Scotland','🏴󠁧󠁢󠁳󠁣󠁴󠁿'),
  ('TUR','Türkiye','🇹🇷'),
  ('UKR','Ukraine','🇺🇦'),
  ('WAL','Wales','🏴󠁧󠁢󠁷󠁬󠁳󠁿'),
  ('POL','Poland','🇵🇱'),
  ('CZE','Czechia','🇨🇿'),
  ('JPN','Japan','🇯🇵'),
  ('KOR','South Korea','🇰🇷'),
  ('IRN','Iran','🇮🇷'),
  ('AUS','Australia','🇦🇺'),
  ('KSA','Saudi Arabia','🇸🇦'),
  ('QAT','Qatar','🇶🇦'),
  ('UZB','Uzbekistan','🇺🇿'),
  ('JOR','Jordan','🇯🇴'),
  ('MAR','Morocco','🇲🇦'),
  ('SEN','Senegal','🇸🇳'),
  ('TUN','Tunisia','🇹🇳'),
  ('EGY','Egypt','🇪🇬'),
  ('ALG','Algeria','🇩🇿'),
  ('NGA','Nigeria','🇳🇬'),
  ('CIV','Côte d''Ivoire','🇨🇮'),
  ('GHA','Ghana','🇬🇭'),
  ('CMR','Cameroon','🇨🇲'),
  ('RSA','South Africa','🇿🇦'),
  ('NZL','New Zealand','🇳🇿')
on conflict (id) do nothing;
